# Generated by Django 3.1.4 on 2021-03-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEnrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('DOB', models.IntegerField()),
                ('addres', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('phone_no', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('class_opted', models.CharField(choices=[('5', '5'), (' 6', '6'), (' 7', '7'), (' 8', '8'), (' 9', '9'), (' 10', '10')], max_length=100)),
                ('marks', models.CharField(max_length=100)),
                ('date_of_joining', models.DateTimeField()),
            ],
        ),
    ]
